# Generated by Django 2.0.7 on 2019-05-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('date_of_meal', models.DateField()),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('images', models.ImageField(blank=True, null=True, upload_to='restaurant')),
                ('similardishes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
